remote_theme: pages-themes/minimal@v0.2.0
url: "https://lmillischer.github.io"

title: Laurent Millischer
description: Research and teaching on all things finance and climate change.

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one